import { Mesh } from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    Room: Mesh;
    Tiles: Mesh;
    Bed_Frame: Mesh;
    Bed_Sheet: Mesh;
    Bed_Pillow: Mesh;
    Bed_Pillow_Small: Mesh;
    Cube037: Mesh;
    Cube037_1: Mesh;
    Cube037_2: Mesh;
    Chair_Back: Mesh;
    Chair_Cushion_Bottom: Mesh;
    Chair_Bottom_Cylinder: Mesh;
    Chair_Wheels_Holder: Mesh;
    Chair_Wheels001: Mesh;
    Chair_Wheels002: Mesh;
    Chair_Wheels003: Mesh;
    Chair_Wheels004: Mesh;
    Chair_Wheels005: Mesh;
    Chair_Handle_Stands: Mesh;
    Chair_Handles: Mesh;
    Chair_Plate: Mesh;
    Chair_Pillow_Bottom: Mesh;
    Chair_Pillow_Top: Mesh;
    Table: Mesh;
    Table_LED: Mesh;
    Cube001: Mesh;
    Cube001_1: Mesh;
    Cube004: Mesh;
    Cube004_1: Mesh;
    Mouse_Wheel: Mesh;
    Mouse_Pad: Mesh;
    Cube005: Mesh;
    Cube005_1: Mesh;
    Cube023: Mesh;
    Cube030: Mesh;
    Cube031: Mesh;
    CPU: Mesh;
    Cube043: Mesh;
    Cube043_1: Mesh;
    Cube033: Mesh;
    Cube034: Mesh;
    Cube035: Mesh;
    Keyboard: Mesh;
    Keyboard_lights: Mesh;
    Keys: Mesh;
    Circle: Mesh;
    Circle_1: Mesh;
    Mug_Hold: Mesh;
    Touch_Grass: Mesh;
    Cube016: Mesh;
    Cube016_1: Mesh;
    Mat_Grass: Mesh;
    Cupboard_Frame: Mesh;
    Cube025: Mesh;
    Cube025_1: Mesh;
    Cupboard_Key_Hole: Mesh;
    Cupboard_Key: Mesh;
    Cupboard_Legs: Mesh;
    Bin: Mesh;
    Bulb: Mesh;
    Bulb_Holder: Mesh;
    Bulb_Wire: Mesh;
    Rack: Mesh;
    Fan_Brain: Mesh;
    Fan_Blades: Mesh;
    Cylinder009: Mesh;
    Cylinder009_1: Mesh;
    Fan_Body: Mesh;
    Fan_Stand: Mesh;
    Fan_Legs: Mesh;
    Buttons_Plate: Mesh;
    Fan_Knob: Mesh;
    Btn_1: Mesh;
    Btn_2: Mesh;
    Btn_3: Mesh;
    Btn_Off: Mesh;
  };
  materials: {
    ////
  };
};
