/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Float, useGLTF } from "@react-three/drei";
import { GLTFResult } from "./model-types";
import { ModelParentGroup } from "./ModelGroup";
import { useRef, useState } from "react";
import { Color, Mesh } from "three";
import { useFrame } from "@react-three/fiber";
import { useSpring } from "@react-spring/three";
import { useControls } from "leva";

export function RoomModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/room.glb") as GLTFResult;

  const fanBladesRef = useRef<Mesh>();
  const [fanBladeSpeedMultiplier, setFanBladeSpeedMultiplier] = useState(1);
  const { springBladeMultiplier } = useSpring({
    springBladeMultiplier: fanBladeSpeedMultiplier,
    config: {
      duration: 1000,
    },
  });

  /// [colors]
  const materialColors = useControls("Material Colors", {
    chairCushionColor: {
      value: "#414141",
      label: "Chair Cushion Color",
    },
    chairPillowColor: {
      value: "#e89646",
      label: "Chair Pillow Color",
    },
    chairHandleColor: {
      value: "#343434",
      label: "Chair Handle Color",
    },
    chairMetalColor: {
      value: "#414141",
      label: "Chair Metal Color",
    },
    chairWheelColor: {
      value: "#414141",
      label: "Chair Wheel Color",
    },
    tableColor: {
      value: "#6f3e19",
      label: "Table Color",
    },
    computerFrameColor: {
      value: "#2a2a2a",
      label: "Computer Frame Color",
    },
    monitorScreenColor: {
      value: "#61ff84",
      label: "Monitor Screen Color",
    },
    mouseLightColor: {
      value: "#ff0000",
      label: "Mouse Light Color",
    },
    mousePadColor: {
      value: "#454545",
      label: "Mouse Pad Color",
    },
    speakerCanvasColor: {
      value: "#525252",
      label: "Speaker Canvas Color",
    },
    speakerButtonColor: {
      value: "#fff",
      label: "Speaker Button Color",
    },
    keyboardColor: {
      value: "#2a2a31",
      label: "Keyboard Color",
    },
    cupHolderColor: {
      value: "#934a00",
      label: "Cup Holder Color",
    },
    mugColor: {
      value: "#c0c0c0",
      label: "Mug Color",
    },
    coffeeColor: {
      value: "#241307",
      label: "Coffee Color",
    },
    grassColor: {
      value: "#3b7811",
      label: "Grass Color",
    },
    matColor: {
      value: "#02522b",
      label: "Mat Color",
    },
    matLettersColor: {
      value: "#ab5e06",
      label: "Mat Letters Color",
    },
    cupboardColor: {
      value: "#b387ff",
      label: "Cupboard Color",
    },
    cupboardMetalColor: {
      value: "#321c4f",
      label: "Cupboard Metal Color",
    },
    cupboardKeyColor: {
      value: "#321c4f",
      label: "Cupboard Key Color",
    },
  });

  useFrame(() => {
    if (!fanBladesRef.current) return;
    fanBladesRef.current.rotation.z += 0.06 * springBladeMultiplier.get();
  });

  return (
    <group {...props} dispose={null}>
      <ModelParentGroup
        floatIntensity={0}
        groupKey="Base"
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Room",
              hoverColor: "#FFFF61",
              hoverContent: "It's just the wall and floor. 🧱",
              showComingSoonLabel: true,
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Tiles",
              hoverColor: "#010112",
              meshMaterial: {
                roughness: 0.5,
              },
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Bin",
              hoverColor: "#fff",
              position: [-3.238, 0.7, -3.282],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Rack",
              hoverColor: "#fff",
              position: [-3.256, 3.233, -1.357],
            },
          },
        ]}
      />
      <ModelParentGroup
        groupKey="Bed"
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Bed_Sheet",
              hoverColor: "#7aadff",
              hoverContent:
                "Smart developers recharge with a \nday-time sleep. 🌞",
              position: [2.325, 1.688, -0.908],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Bed_Pillow",
              hoverColor: "#C3C5FF",
              position: [2.473, 1.925, -0.311],
              rotation: [-Math.PI, 0.657, -Math.PI],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Bed_Pillow_Small",
              hoverColor: "#C3C5FF",
              position: [1.404, 1.846, 1.352],
              rotation: [-Math.PI, 1.299, -Math.PI],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Bed_Frame",
              hoverColor: "#7F4B4B",
              position: [2.347, 1.494, -0.872],
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Phone",
              position: [2.479, 1.758, 1.078],
              rotation: [0, -0.194, 0],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube037",
                    hoverColor: "#0f0f0f",
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube037_1",
                    hoverColor: "#0f0f0f",
                    meshMaterial: {
                      roughness: 0.4,
                    },
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube037_2",
                    hoverColor: "#0f0f0f",
                    meshMaterial: {
                      roughness: 0.6,
                    },
                  },
                },
              ],
            },
          },
        ]}
      />
      <ModelParentGroup
        groupKey="Chair"
        position={[-0.707, 1.979, 1.904]}
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Chair_Back",
              hoverColor: materialColors.chairCushionColor,
              hoverContent: "🏆 Achievement unlocked:\nComfort Level 100",
              hoverContentTheme: "dark",
              meshMaterial: {
                roughness: 0.6,
              },
            },
          },

          {
            childType: "group",
            props: {
              groupKey: "Chair_Bottom",
              position: [-0.615, -0.508, 0],
              rotation: [0, -1.571, 0],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Chair_Cushion_Bottom",
                    hoverColor: materialColors.chairCushionColor,
                  },
                },
                {
                  childType: "group",
                  props: {
                    groupKey: "Chair_Wheels",
                    position: [0, -0.196, -0.152],
                    rotation: [0, 1.571, 0],
                    elements: [
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Bottom_Cylinder",
                          hoverColor: materialColors.chairMetalColor,
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels_Holder",
                          hoverColor: materialColors.chairMetalColor,
                          position: [0, -0.499, 0],
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels001",
                          hoverColor: materialColors.chairWheelColor,
                          position: [0.882, -0.653, 0.002],
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels002",
                          hoverColor: materialColors.chairWheelColor,
                          position: [0.271, -0.653, 0.839],
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels003",
                          hoverColor: materialColors.chairWheelColor,
                          position: [0.274, -0.653, -0.838],
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels004",
                          hoverColor: materialColors.chairWheelColor,
                          position: [-0.712, -0.653, -0.52],
                        },
                      },
                      {
                        childType: "mesh",
                        props: {
                          modelKey: "Chair_Wheels005",
                          hoverColor: materialColors.chairWheelColor,
                          position: [-0.715, -0.653, 0.517],
                        },
                      },
                    ],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Chair_Handle_Stands",
                    hoverColor: materialColors.chairHandleColor,
                    position: [0.061, 0, 0],
                    rotation: [0, 1.571, 0],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Chair_Handles",
                    hoverColor: materialColors.chairHandleColor,
                    position: [-0.79, 0.329, 0.032],
                    rotation: [0, 1.571, 0],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Chair_Plate",
                    hoverColor: materialColors.chairMetalColor,
                    position: [0, -0.149, -0.152],
                    rotation: [0, 1.571, 0],
                  },
                },
              ],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Chair_Pillow_Bottom",
              hoverColor: materialColors.chairPillowColor,
              position: [0.225, 1.308, 0],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Chair_Pillow_Top",
              hoverColor: materialColors.chairPillowColor,
              position: [-0.148, -0.285, 0],
            },
          },
        ]}
      />
      <ModelParentGroup
        groupKey={["Computer", "1"]}
        floatIntensity={0}
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Table",
              hoverColor: materialColors.tableColor,
              position: [0.044, 0, 0.783],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "CPU",
              hoverColor: materialColors.computerFrameColor,
              position: [-2.955, 1.008, 3.21],
            },
          },
        ]}
      />
      /// [Computer Motion]
      <ModelParentGroup
        groupKey={["Computer", "2"]}
        elements={[
          {
            childType: "group",
            props: {
              groupKey: "Monitor",
              position: [-3.22, 2.848, 2.971],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube001",
                    hoverColor: materialColors.computerFrameColor,
                    meshMaterial: {
                      roughness: 0.8,
                    },
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube001_1",
                    hoverColor: materialColors.monitorScreenColor,
                    hoverContent:
                      "Don't worry, it's not judging your code...or is it? 💻",
                    meshMaterial: {
                      roughness: 0.2,
                    },
                  },
                },
              ],
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Mouse",
              position: [-2.737, 2.078, 1.212],
              rotation: [0, 0.337, 0],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube004",
                    hoverColor: materialColors.computerFrameColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube004_1",
                    hoverColor: materialColors.mouseLightColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Mouse_Wheel",
                    hoverColor: materialColors.computerFrameColor,
                    position: [-0.061, -0.004, 0],
                  },
                },
              ],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Mouse_Pad",
              hoverColor: materialColors.mousePadColor,
              position: [-2.67, 2.057, 1.117],
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Speaker_A",
              position: [-3.239, 2.164, 3.556],
              rotation: [0, 0.542, 0],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube005",
                    hoverColor: materialColors.computerFrameColor,
                    meshMaterial: {
                      roughness: 0.6,
                    },
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube005_1",
                    hoverColor: materialColors.speakerCanvasColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube023",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.077, -0.08, 0.061],
                    rotation: [0, 0, 0.242],
                    scale: [0.085, 0.114, 0.102],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube030",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.077, -0.08, 0.032],
                    rotation: [0, 0, 0.242],
                    scale: [0.085, 0.114, 0.102],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube031",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.081, -0.079, 0.009],
                    rotation: [0, 0, 0.242],
                    scale: [0.01, 0.029, 0.026],
                  },
                },
              ],
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Speaker_B",
              position: [-3.535, 2.164, 1.459],
              rotation: [0, -0.315, 0],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube005",
                    hoverColor: materialColors.computerFrameColor,
                    meshMaterial: {
                      roughness: 0.6,
                    },
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube005_1",
                    hoverColor: materialColors.speakerCanvasColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube023",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.077, -0.08, 0.061],
                    rotation: [0, 0, 0.242],
                    scale: [0.085, 0.114, 0.102],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube030",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.077, -0.08, 0.032],
                    rotation: [0, 0, 0.242],
                    scale: [0.085, 0.114, 0.102],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube031",
                    hoverColor: materialColors.speakerButtonColor,
                    position: [0.081, -0.079, 0.009],
                    rotation: [0, 0, 0.242],
                    scale: [0.01, 0.029, 0.026],
                  },
                },
              ],
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Keyboard",
              position: [-2.737, 2.074, 2.217],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Keyboard",
                    hoverColor: materialColors.keyboardColor,
                    meshMaterial: {
                      roughness: 0.6,
                    },
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Keyboard_lights",
                    hoverColor: materialColors.computerFrameColor,
                    position: [-0.051, 0.017, -0.37],
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Keys",
                    hoverColor: materialColors.computerFrameColor,
                    position: [0.042, 0.017, -0.502],
                  },
                },
              ],
            },
          },
        ]}
      />
      /// [Mug]
      <ModelParentGroup
        groupKey="Mug"
        floatIntensity={0}
        elements={[
          {
            childType: "group",
            props: {
              groupKey: "Cup",
              position: [-2.692, 2.053, 3.406],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Circle",
                    hoverColor: materialColors.mugColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Circle_1",
                    hoverColor: materialColors.coffeeColor,
                  },
                },
              ],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Mug_Hold",
              hoverColor: materialColors.cupHolderColor,
              hoverContent: "Caffeine: The programmer's fuel. ☕",
              hoverContentTheme: "dark",
              position: [-2.692, 2.05, 3.406],
            },
          },
        ]}
      />
      /// [TouchGrass]
      <ModelParentGroup
        groupKey="TouchGrass"
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Touch_Grass",
              position: [-2.955, 0.512, 1.681],
              hoverColor: materialColors.matLettersColor,
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Mat_Plain",
              position: [-2.955, 0.475, 1.681],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube016_1",
                    hoverColor: materialColors.matColor,
                    hoverContent: "Go Touch Grass! 🌱",
                    hoverContentTheme: "dark",
                  },
                },
              ],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Mat_Grass",
              hoverColor: materialColors.grassColor,
              outlineOpacity: 0,
            },
          },
        ]}
      />
      <ModelParentGroup
        groupKey="Cupboard"
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Cupboard_Frame",
              hoverColor: materialColors.cupboardColor,
              position: [-1.186, 3.455, -3.061],
              hoverContent: "No skeletons here, just old code. 🪶",
              showComingSoonLabel: true,
            },
          },
          {
            childType: "group",
            props: {
              groupKey: "Cupboard_Dors",
              position: [-2.705, 3.206, -2.399],
              elements: [
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube025",
                    hoverColor: materialColors.cupboardColor,
                  },
                },
                {
                  childType: "mesh",
                  props: {
                    modelKey: "Cube025_1",
                    hoverColor: materialColors.cupboardMetalColor,
                  },
                },
              ],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Cupboard_Key_Hole",
              hoverColor: materialColors.cupboardMetalColor,
              position: [-1.038, 2.585, -2.399],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Cupboard_Key",
              hoverColor: materialColors.cupboardKeyColor,
              position: [-1.038, 2.585, -2.398],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Cupboard_Legs",
              hoverColor: materialColors.cupboardMetalColor,
              position: [-1.186, 3.455, -3.061],
            },
          },
        ]}
      />
      <ModelParentGroup
        groupKey="Bin"
        onClick={() => {}}
        onHover={null}
        elements={[
          {
            childType: "mesh",
            props: {
              modelKey: "Bin",
              hoverColor: "#fff",
              position: [-3.238, 0.7, -3.282],
            },
          },
          {
            childType: "mesh",
            props: {
              modelKey: "Rack",
              hoverColor: "#fff",
              position: [-3.256, 3.233, -1.357],
            },
          },
        ]}
      />
      {/* <mesh
        name="Rack"
        castShadow
        receiveShadow
        geometry={nodes.Rack.geometry}
        material={nodes.Rack.material}
        position={[-3.256, 3.233, -1.357]}
      /> */}
      {/* <mesh
        name="Bin"
        castShadow
        receiveShadow
        geometry={nodes.Bin.geometry}
        material={nodes.Bin.material}
        position={[-3.238, 0.7, -3.282]}
      /> */}
    </group>
  );
}

useGLTF.preload("/room.glb");
